### ISSUE TITLE
Confusing instruction "Download all ACCOUNT STATEMENT documents" in README.md

### ISSUE THREAD

**Issue by milech** [jczaja/e-trade-tax-return-pl-helper#112]
It seems that loading only the "ACCOUNT STATEMENT" files, as displayed on [Accounts -> Documents -> Statements](https://edoc.etrade.com/e/t/onlinedocs/docsearch?doc_type=stmt) and guided by the readme file in point 2.iii,  is not sufficient for calculating incomes and taxes. Uploading only these documents either causes the error provided below (behavior observed by me) or substantially decreases the income (behavior observed by a colleague):

```
2024-04-11T12:42:22.014Z ERROR [etradeTaxReturnHelper::logging]

ERROR: Sold transaction in Gain&Losses:
 (trade_date: 09/05/2023, acquisition date: 07/31/2023, cost basis: 0, income: <value removed by me>) exist,
 but corressponding data from PDF document is missing. You can download account statements PDF documents at:

            https://edoc.etrade.com/e/t/onlinedocs/docsearch?doc_type=stmt


thread 'main' panicked at src\logging.rs:24:10:


ERROR: Sold transaction in Gain&Losses:
 (trade_date: 09/05/2023, acquisition date: 07/31/2023, cost basis: 0, income: <value removed by me>) exist,
 but corressponding data from PDF document is missing. You can download account statements PDF documents at:

            https://edoc.etrade.com/e/t/onlinedocs/docsearch?doc_type=stmt
```

It seems that all .pdf files (except for "MS_2023_XXXXX_XXXX_XXXXXXXX.pdf" and "TY 2023-XXXX-X-XXXX.pdf") are needed for proper calculations (ACCOUNT STATEMENT, Single Account Statement, and Recap of Cash Management Activity). When "Recap of Cash Management Activity" is not loaded, the income from dividends is substantially decreased.

Please, update the README.md file so that it precisely states which documents shall be added, preferably using names as they are displayed by E-Trade on [Accounts -> Documents -> Statements](https://edoc.etrade.com/e/t/onlinedocs/docsearch?doc_type=stmt).

**Comment by jczaja** [comment]
@milech Thanks for reporting problems. I have added "Single Account Statement" to instruction. As for "Recap of Cash Management Activity" according to my usnderstand it should not be needed. So I would like to hear more on this.

**Comment by milech** [comment]
Awesome! Thank you!
Regarding "Recap of Cash Management Activity" you're right - it's not needed. It was my mistake caused by the way the recap file is being downloaded from E-trade. In case `Recap of Cash Management Activity` and `Single Account Statement` are identically dated, they are being downloaded under the same filename and thus it's easy to confuse them.

As you have added the `Single Account Statement` to the manual, I'm closing this issue as completed.
