### ISSUE TITLE
etradeTaxReturnHelper-0.2.1.zip contains 2 identical copies of etradeTaxReturnHelper.exe

### ISSUE THREAD

**Issue by serge-s** [jczaja/e-trade-tax-return-pl-helper#46]
etradeTaxReturnHelper-0.2.1.zip contains 2 identical copies of etradeTaxReturnHelper.exe - one in the root, another in the 'deps' directory.

**Comment by jczaja** [comment]
@serge-s I made a fix and starting from release 0.2.2 it has only one copy of binary. Thanks for reporting a problem!
